services:
  - type: web
    name: kuphilgraduate
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn --chdir graduateCheck graduateCheck.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://*.onrender.com" 